/*
 * 파일명 : MGSGameplayTags.h
 * 생성자 : 장대한
 * 생성일 : 2026-03-01
 * 수정자 : 김동석
 * 수정일 : 2026-03-06
 */

#pragma once

#include "NativeGameplayTags.h"

namespace MGSGameplayTags
{
	// Input tags: Enhanced Input -> GAS bridge
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Move)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Look)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Jump)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Sprint)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Walk)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Crouch)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Strafe)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Aim)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Fire)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Reload)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Interact)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Primary)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Secondary)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(InputTag_Weapon_Throwable)

	// Ability tags: identify gameplay abilities
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Jump)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Sprint)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Walk)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Crouch)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Aim)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Fire)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Reload)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Interact)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Equip_Primary)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Equip_Secondary)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Ability_Player_Equip_Throwable)

	// Weapon tags: carried/equipped weapon identifier
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Player_Primary)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Player_Secondary)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Weapon_Player_Throwable)

	// State tags: runtime avatar state
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Movement_Sprint)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Movement_Run)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Movement_Walk)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Movement_Falling)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Movement_WantsToSprint)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Crouching)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Aiming)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_CombatReady)
	
	// 상태 태그 (gait)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Gait_Walk);
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Gait_Run);
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Gait_Sprint);
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_JustLanded_Light);
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_JustLanded_Heavy);

	// 상태 태그 (Stance)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Stance_Stand);
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Stance_Crouch);

	// 상태 태그 (MovementMode)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Mode_OnGround);
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_Mode_InAir);

	// 카메라와의 거리에 따른 태그(플레이어는 Dense)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_LOD_Dense);        
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_LOD_Sparse);       
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Player_LOD_ExtremeSparse);
	
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Clear)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Suspicious)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Investigation)
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(State_Enemy_Combat)

	// Event tags: gameplay event payload trigger
	MGSPROJECT_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Player_Interact)
}
